apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  labels:
    app: grpc-server
  namespace: go-microservices
spec:
  type: LoadBalancer
  ports:
    - name: "50051"
      port: 50051
      targetPort: 50051
  selector:
    app: grpc-server
