apiVersion: v1
kind: Service
metadata:
  name: restful-api
  labels:
    app: restful-api
  namespace: go-micro-service
spec:
  type: LoadBalancer
  ports:
    - name: "1323"
      port: 1323
      targetPort: 1323
  selector:
    app: restful-api
