apiVersion: v1
kind: Secret
metadata:
  name: gms-database
  namespace: go-microservices
stringData:
  HOST: postgres
  PORT: "5432"
  PASSWORD: postgres
  USER: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: gms-grpc
  namespace: go-microservices
stringData:
  HOST: grpc-server
  PORT: "50051"
  TARGET_PORT: "50051"
---
apiVersion: v1
kind: Secret
metadata:
  name: gms-api
  namespace: go-microservices
stringData:
  PORT: "1323"
  TARGET_PORT: "1323"
