version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: PGPASSWORD=postgres psql -h localhost -U postgres -c '\q'
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

volumes:
  postgresql:
    name: postgresql
